jar: GwtAppCommonModule


resources: 
- $source$
- src|**.xml
- LICENSE

compiledependencies:
- ../LiteSoftDeferred
- ../LiteSoftExternalization
- ../LiteSoftCommonFoundation

compileclasspath:
- libs/client|**.jar
