jar: GwtAppCommonModule


resources: 
- $source$
- src|**.xml
- LICENSE

dependencies:
- ../LiteSoftDeferred
- ../LiteSoftExternalization
- ../LiteSoftCommonFoundation

compileclasspath:
- libs|**.jar
